### ISSUE TITLE
i2c playing closely spaced notes crashes W/syn

### ISSUE THREAD

**Issue by csboling** [whimsicalraps/wslash#63]
w20b4.zip, crow-931e0d967a44f786d94494d8f047a20c3ea13e6d.zip

I tripped over this while attempting to implement W/syn support on Ansible. As soon as I would put two voices on the same Kria sequence step, W/ would shortly crash. After this the orange light over IN continues to blink as notes are sent but no sound is made. In this state sending CV triggers to THAT does not produce sound either.

Here is a way to reproduce the behavior with crow. `play_voice` using multiple voices this way also seems affected.

```lua
function play_one(n, v)
  ii.wsyn.play_note(n, v)
  delay(function() ii.wsyn.play_note(n, 0) end, 0.1)
end

function play()
  print('play')
  play_one(0, 5)
  -- uncomment this for crash after a few notes:
  -- play_one(1, 5)
end

beat = metro.init{ event = play
		 , time = 1.0
		 }
function init()
  ii.wsyn.ar_mode(0)
  beat:start()
  print('ok')
end
```

**Comment by csboling** [comment]
Same behavior is present in w2b05,

**Comment by trentgill** [comment]
@csboling i just saw this  issue (thanks for cataloging it here)! turns out the poly-allocator was super messed up. so i rebuilt it, only to realize i'd already done the exact same thing for JF (with no recollection of having done so!)...

the fix is w20b7 which i'm posting shortly.

one red herring that i thought was the cause is that the crow `delay(fn, time, repeats)` function was defaulting to `repeat=1` (should be `=0`) meaning it would be called twice. i've fixed it in `crow:main` but just a little FYI until we make a new crow release.

**Comment by csboling** [comment]
Excellent, this is the last thing preventing me from declaring Ansible leader mode support for W/syn and crow good-to-go.
